config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  root 'recipies#index'
 
  resources :recipies do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

 has_many :recipy_ingredients
 has_many :recipies, through: :recipy_ingredients
 accepts_nested_attributes_for :recipy_ingredients, allow_destroy: true

 validates :name, presence: true, uniqueness: true
end

app/models/recipy.rb
class Recipy < ApplicationRecord


  has_many :recipy_ingredients
  has_many :ingredients, through: :recipy_ingredients
  
  has_one_attached :image
  accepts_nested_attributes_for :recipy_ingredients, allow_destroy: true

  def self.to_csv
   CSV.generate do |csv|
      csv << column_names
          all.each do |recipy|
            csv << recipy.attributes.values_at(*column_names)
          end
      end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      recipy = find_by_id(row["id"]) || new
      recipy.attributes = row.to_hash
      recipy.save!
    end
  end



end

app/models/recipy_ingredient.rb
class RecipyIngredient < ApplicationRecord
    belongs_to :recipy
    belongs_to :ingredient
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
  end

  def create
  
    @ingredient = Ingredient.new(ingredient_params)
      if @ingredient.save
        redirect_to ingredients_path, notice: "Ingredient was successfully created."
      else
        render :new, status: :unprocessable_entity 
      end
  end

  def update
  
      if @ingredient.update(ingredient_params)
        redirect_to ingredients_path, notice: "Ingredient was successfully updated."
      else
        render :edit, status: :unprocessable_entity 
      end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
      redirect_to ingredients_path, notice: "Ingredient was successfully destroyed." 
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController
  before_action :set_recipy, only: %i[ show edit update destroy ]
  protect_from_forgery except: :create

  def index
    @recipies = Recipy.all
    @recipy = Recipy.new
    @ingredients = Ingredient.all
    
    # To Export files

    respond_to do |format|
      format.html
      format.csv { send_data @recipies.to_csv }
    end
  end
  
  # To import File

  def import
    
   if Recipy.import(params[:file])
    redirect_to root_path, notice: "File imported" 
   else
   redirect_to root_path
   end 
  end 

  def show
    @ingredients = Ingredient.all
  end

  def new
    @recipy = Recipy.new
    @ingredients = Ingredient.all
  end 
  
  def create
    @recipy = Recipy.new(recipy_params)
    if @recipy.save
      redirect_to recipies_path, notice: "Recipy was successfully created."
    else
        render :new, status: :unprocessable_entity  
      end
  end
  
  def edit
    @recipy = Recipy.new
    @ingredients = Ingredient.all
  end

  def update
    respond_to do |format|
      if @recipy.update(recipy_params)
        format.html { redirect_to recipy_url(@recipy), notice: "Recipy was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipy.destroy
    respond_to do |format|
      format.html { redirect_to recipies_url, notice: "Recipy was successfully destroyed." }
    end
  end

  private
  
    def set_recipy
      @recipy = Recipy.find(params[:id])
    end

    def recipy_params
      params.require(:recipy).permit(:name, :procedure,:image, recipy_ingredients_attributes: [:_destroy,:id,:quantity,:unit,:ingredient_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end
 

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipies_helper.rb
module RecipiesHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>

  <div class="field form-label mb-3"">
    <%= form.label :name %>
    <%= form.text_field :name,autocomplete: 'off' %>
  </div>
  <div class="actions ms-5">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Reciper", recipies_path,:class=>"nav-link navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Recipies', recipies_path,:class=>"nav-link"  %> 
      </li> 
        <li class="nav-item">
          <%= link_to "Ingredients", ingredients_path,:class=>"nav-link" %>
        </li> 
        <li class="nav-item">
         <%= link_to "New Ingredient", new_ingredient_path,:class=>"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/ingredients/edit.html.erb
<%= render "ingredients/navbar" %>

<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<%= render "ingredients/navbar" %>


<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table class="table table-striped table-hover">
  <thead class="heading">
    <tr>
      <th scope="col"style='color:cadetblue'></th>
      <th scope="col"style='color:cadetblue'>Name</th>
      <th scope="col"style='color:cadetblue'> Actions </th>
      <th scope="col"style='color:cadetblue'></th>
      <th scope="col"style='color:cadetblue'></th>
    </tr>
  </thead>
  <tbody>
  <% @ingredients.each do |ingredient| %>
    <tr>
      <th scope="row">*</th>
      <td style='color:cadetblue'><%= ingredient.name %></td>
      <td><%= link_to 'View', ingredient %></td>
      <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
      <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/ingredients/new.html.erb
<%= render "ingredients/navbar" %>

<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>
<div class=ms-5>
<%= link_to 'Back', ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<%= render "ingredients/navbar" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reciper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'ingredients', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/recipies/_edit.html.erb
<%= render 'form', recipy: @recipy %>

app/views/recipies/_form.html.erb
<div class="modal-body">
  <%= nested_form_for recipy, remote: true, local: false do |f| %>
    <% if recipy.errors.any? %>
    <ul>
    <% recipy.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
      <div class="mb-3">
      <label for="recipeName" class="form-label">Recipe Name</label>
      <%= f.text_field :name, {id: "recipeName", class: "form-control", type: "text",autocomplete: 'off',required: true } %>
    </div>
    <div class="mb-3">
      <label for="recipeImage" class="form-label">Choose image</label>
      <%= f.file_field :image, {id: "recipeImage", class: "form-control", type: "file", accept:'image/*',required: true  } %>
    </div>
    <div class="mb-3">
      <label for="recipeProcedure" class="form-label">Cooking Procedure</label>
      <%= f.text_field :procedure, {id: "recipeProcedure", class: "form-control", type: "text",autocomplete: 'off',required: true  } %>
    </div>
    <%= f.fields_for :recipy_ingredients do |ingredients_form|%>
      <div class="input-group row">
        <div class="mb-3 col-md-4">
          <label for="ingredient-name" class="form-label">Ingredient</label>
          <%= ingredients_form.collection_select :ingredient_id, @ingredients, :id,:name,{}, {:class => 'form-select'} %>  </div>

        <div class="mb-3 col-md-4">
          <label for="ingredient-quantity" class="form-label">Quantity</label>
          <%= ingredients_form.text_field :quantity, {id: "ingredient-quantity", class: "form-control", type: "number" } %>
        </div>
          <%# <%= ingredients_form.text_field :unit, {class: "form-control", type: "text" } %> 
       <div class="mb-3 col-md-4">
          <label for="unit" class="form-label">Unit</label>
          <div>
        <%= ingredients_form.select(:unit, options_for_select([['Kg','Kg'],['grams','grams'],['ltr','ltr']])) %>
         </div>
         </div>
      </div>
      <%= ingredients_form.link_to_remove "Remove Ingredient" %>
    <% end %>
    <p><%= f.link_to_add "Attach Ingredient", :recipy_ingredients %></p>
    <% if params[:action] == 'index' %>
       <button type="submit" class="btn btn-primary" id="btn">Create Recipe</button>
     <%end%>  
     <% if params[:action] == 'show' %>
      <button type="submit" class="btn btn-primary" id="btn">Update Recipe</button>
     <%end%>
  <% end %>
</div>


<script>

$('#btn').click(function(){
  $.ajax({
    type: "GET",
    dataType: 'json',      
    url: "/recipie",
    success: function (result) {
      $('#staticBackdrop').modal('hide')
    },
    error: function (result, err) {
      $('#staticBackdrop').modal('show')
    }
  });
});

</script>

app/views/recipies/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Reciper", recipies_path,:class=>"nav-link navbar-brand" %>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
       <% if params[:action] == 'index' %>
        <button type="button" class="btn btn-primary" id="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" data-dismiss="modal" aria-hidden="true" remote=true ">
          Create Recipies
        </button>
        <% end %>
         <% if params[:action] == 'show' %>
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Edit
          </button>
          <% end %>
        <li class="nav-item">
          <%= link_to "Ingredients", ingredients_path,:class=>"nav-link" %>
        </li> 
        <li class="nav-item">
         <%= link_to "New Ingredient", new_ingredient_path,:class=>"nav-link" %>
        </li>
      </ul>
    </div>  
  </div>
</nav>

app/views/recipies/_recipy.html.erb
<div class="col">
    <div class=" card" style="width: 18rem;" >
      <% if recipy.image.present? %>
        <%= link_to image_tag(recipy.image, style:'width:100%'), recipy_path(recipy), :class=>"card-img-top" %>
      <% end%>  
    <div class="card-body">
      <h6 class="card-title">Name</h6>
      <p class="card-text"><%= recipy.name %></p>
      <h6 class="card-title">Procedure</h6>
      <p class="card-text"><%= recipy.procedure %></p>
    <%= link_to 'Destroy', recipy, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  </div>
</div>

app/views/recipies/create.js.erb
$('#row').empty();
$("#row").append("<%= j render @recipy %>")

app/views/recipies/index.html.erb
<%= render "recipies/navbar" %>

 <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Create New Recipe</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      
      <%= render 'form', recipy: @recipy %>
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

<div>
  <p class="notice"><%= notice %></p>
</div>
<div>
Download file:
<%= link_to CSV, recipies_path(format:'csv')%>
</div><br>
  <div id="cre">
    <h1>Recipies</h1>
  </div>

  <tbody id="table">
   
<div class="container">
<div class="row">
<% @recipies.each do |recipy| %>
  <%= render 'recipy', recipy:recipy %>
<% end %>
</div>
</div> 
</tbody>


<h4>Import CSV Files only</h4>

<%= form_tag import_recipies_path, multipart: true do %>
  <%= file_field_tag :file, accept: 'text/csv',required: true  %>
  <%= submit_tag "Import"%>
<% end %>

app/views/recipies/new.html.erb
<h1>New Recipy</h1>

<%= render 'form', recipy: @recipy %>
 
<%= link_to 'Back', recipies_path %>

app/views/recipies/show.html.erb
<%# for navbar %>

<%= render "recipies/navbar" %>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Editing Recipe</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <%= render 'edit', recipy:@recipy %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="d-inline"><p id="notice"><%= notice %></p></div>

<%= link_to image_tag(@recipy.image, style:'width:100%; height: 350px;'), recipies_path,:class=>'img' %>



<table class="table table-striped table-hover">
  <thead class="heading">
    <tr>
      <th scope="col"style='color:cadetblue'></th>
      <th scope="col"style='color:cadetblue'>Ingredients</th>
      <th scope="col"style='color:cadetblue'>Quantity</th>
      <th scope="col"style='color:cadetblue'>Unit</th>
    </tr>
  </thead>
  <tbody>


     <p> Name of the Recipe is: <b><%= @recipy.name %></b></p>
      <p>Procedure is:<b><%= @recipy.procedure %><b></p>
  <% @recipy.recipy_ingredients.each do |ingredient| %>
    <tr>
      <th scope="row">*</th>
      <td><% i = Ingredient.find(ingredient.ingredient_id) %>
    <%= i.name %></td>
      <td><%= ingredient.quantity %></td>
      <td><%= ingredient.unit %></td>
    </tr>
    <% end %>
  </tbody>
</table>